name: e2e_interop_test
description: End-to-end test for node interop and builders
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.16.8
  build_runner: ^1.12.2
  build_node_compilers:
    git:
      url: https://github.com/blaueeiner/node-interop
      path: ./build_node_compilers/
      ref: feature/update-dependencies
  js: ^0.6.3
  node_interop:
    git:
      url: https://github.com/blaueeiner/node-interop
      path: ./node_interop/
      ref: feature/update-dependencies
