name: build_node_compilers
version: 0.3.2
description: Builders wrapping DDC and dart2js compilers configured to output Node modules.
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bazel_worker: ^1.0.0
  build: ^2.0.0
  build_config: ^0.4.7
  build_modules: ^3.0.6
  collection: ^1.15.0
  crypto: ^3.0.0
  logging: ^1.0.0
  meta: ^1.3.0
  node_preamble: ^2.0.0
  path: ^1.8.0
  pool: ^1.5.0
  scratch_space: ^1.0.0

dev_dependencies:
  build_test: ^2.0.0
  pedantic: ^1.11.0
  test: ^1.16.8
  a:
    path: test/fixtures/a
  b:
    path: test/fixtures/b
