name: node_interop
description: Provides Dart bindings and utility functions for core Node.js modules.
version: 2.0.0-nullsafety.0
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  js: ^0.6.3

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  build_runner: ^1.12.2
  build_node_compilers:
    git:
      url: https://github.com/blaueeiner/node-interop.git
      path: ./build_node_compilers/
      ref: master
  build_test: ^2.0.0
